---
title: "Coursework for Introduction for Data Science"
output: html_notebook
---


# Question 1
## 1 Part a.

```{r, eval = TRUE, echo = TRUE, }
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 



read_lines(here("data","nasa_global_temperature.txt"), n_max = 10) #Review delim type  

nasa_temp_raw <- read_table(here("data","nasa_global_temperature.txt"), skip = 3)#Save data into name for extract and "skip" cuts out unnecessary data

nasa_temp <- nasa_temp_raw %>% #Tidy up data and save name as requested 
  select("Year", "No_Smoothing") %>% #Selecting column
  mutate(Year = parse_date(Year, format = "%Y")) %>% #Converting char type to date type
  slice(2:142) %>% #Get rid of first line of useless data
  rename(date = Year, temp = No_Smoothing) #Rename column as requested
  
nasa_temp %>% #apply pipe function to saved data set
  ggplot(mapping = aes(x = date, y = temp)) + #Defining graph aesthetics
  geom_line() +#Choosing graph and visualizing data
  labs( #Define titles
    x = "Year", #Visual title for x-axis
    y = "Average tempature arcross global surfaces in °C" #Visual title for y-axis
      )

```
## 1 Part b. 
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

read_lines(here("data", "nasa_arctic_sea_ice.csv"), n_max = 10) #Review delim type

nasa_ice_raw <- read_csv2(here("data", "nasa_arctic_sea_ice.csv")) #Save data into name for extract

nasa_ice_untidy <- tibble(nasa_ice_raw) #Transfer data set to tibble

nasa_ice <- nasa_ice_untidy %>% #apply pipe function to saved data set
  select("year", "extent") %>%#Select relevant column as requested
  rename(date = year, ice = extent) %>% #rename column 
  mutate(date = as.character(date)) %>% #Covert to char in-order to parse to date
  mutate(date = parse_date(date, format = "%Y")) #can't parse unless is char
         
nasa_ice %>% #apply pipe function to saved data set
  ggplot(mapping = aes(x = date, y = ice)) + #Defining graph aesthetics
  geom_line() + #Choosing graph and visualizing data
  labs( #Define titles
    x = "Year", #Visual title for x-axis
    y = "Minimum arctic sea ice extent in million square km" #Visual title for y-axis
  )

```
## 1 part c.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

read_lines(here("data", "nasa_sea_level.csv"), n_max = 50) #Review delim type and check how many to skip

nasa_sea_raw <- read_table(here("data", "nasa_sea_level.csv"), skip = 48, col_names = FALSE) #read data, no column name, hence "col_names" = FALSE

nasa_sea_untidy <- tibble(nasa_sea_raw) # transfer data into tibble

nasa_sea <- nasa_sea_untidy %>% #Save as requested in question
  select(X3, X12) %>% #Select relevant roles
  rename(sea = X12, date = X3) %>% #Name as requested by question
  mutate(date = date_decimal(date, tz = "UTC")) %>% #Converting decimal year "UTC" into datetime
  mutate(date = date(date)) #Converting date decimals into date as requested

nasa_sea %>% #Apply pipe function for visualization
  ggplot(mapping = aes( x = date, y = sea)) + #Defining graph aesthetics
  geom_line() + #Choosing graph and visualizing data
  labs( #Define graph titles
    x = "Year", #Visual title for x-axis
    y = "Change in sea level compared to a reference year in mm" #Visual title for y-axis
  )
```
## 1 part d.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

read_lines(here("data", "nasa_carbon_dioxide.txt"), n_max = 55) #Review delim type and check how many to skip

nasa_co2 <- read_table(here("data", "nasa_carbon_dioxide.txt"), skip = 52) %>% #read data as per type
  select(average, alized) %>% #Select relevant roles
  rename(date = average, co2 = alized) %>% #Name as requested by question
  mutate(date = date_decimal(date, tz = "UTC")) %>% #Converting decimal year "UTC" into datetime
  mutate(date = as_date(date)) %>% #Converting a datetime to date
  mutate(date = floor_date(date, unit = "month")) %>%
  filter(!co2 < 1) #Get rid of outliers

nasa_co2 # To check table

#alternative for getting rid of outliers is mutate(co2 = ifelse(co2 < 1 , NA, co2)) but now it is the same as clean data

nasa_co2 %>% #Apply pipe function for visualization
  ggplot(mapping = aes( x = date, y = co2)) + #Defining graph aesthetics
  geom_point() + #Choosing graph and visualizing data
  labs(  #Define graph titles
    x = "Year", #Visual title for x-axis
    y = "Average global CO2 level in parts per million (ppm)" #Visual title for y-axis
  )



```
## 1 part e.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" & "dplyr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 



nasa <- nasa_temp %>% #first merge, total = 3 merge as 4 files
  full_join(nasa_ice, #Merge with nasa_ice, full join retains all info
            by = c("date" = "date"), #Select column to match contents
            keep = FALSE) %>% #Second merge
  full_join(nasa_sea, #nasa temp+ice now merge with sea
            by = c("date" = "date"), #Select column to match contents
            keep = FALSE) %>% #Last merge
  full_join(nasa_co2, #nasa temp+ice+sea now merge with co2
            by = c("date" = "date"), #Select column to match contents
            keep = FALSE)

nasa #Run code to check table

  
```
## 1 part f.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("lubridate") #Enable function relating to dates 
library("ggrepel") # Adds improved labeling compared to standard ggplot2
library("RColorBrewer") # Load this color package 

nasa %>% #Data for visualization
  select(date, temp, co2) %>% #Select relevant variables  
  filter(date >= "1960-01-01" & date <= "2020-01-01") %>% #Select appropriate dates
  ggplot(mapping = aes(x = co2, y = temp, colour = date)) + #Define graph aesthetics
  geom_point(size = 2) + #Graph uses points and make size to 2
  labs( #Define graph titles
  x = "Average global CO2 level in parts per million (ppm)", # Naming x-axis as request
  y = "Average tempature across global surfaces in °C", # Naming y-axis as request 
  title = "Global surface tempature VS Global CO2 levels in year 1960-2020", # Set title of graph
  colour = "Year") #sequential color spectrum displaying difference years
  
```
# Question 2
## 2 part a.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

historic_co2 <- read_table(here("data", "luthi_carbon_dioxide.txt"), skip = 773) %>% #Read table, skip by prompt from question
  rename(co2 = `CO2(ppmv)`) %>% #Rename column as requested
  rename(yrbp = `Age(yrBP)`) #Rename column as requested

historic_co2 #To check table

```
## 2 part b.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

yrbp_new <- historic_co2 %>% # New data set preparing for the join function later
  mutate(yrbp = yrbp + 13) #Update column names and vales to yrbp, present year =2021

combined_co2 <- nasa_co2 %>% #Save variable as requested
  mutate(yrbp = year(date)) %>% #Covert date to year only
  mutate(yrbp = 2021 - yrbp) %>% #Calculate year before present
  select(co2, yrbp) %>% #Select relevant columns
  group_by(yrbp) %>% #Gather yrbp to correctly summaries average co2 for same years 
  summarise(avg_co2 = mean(co2, na.rm = TRUE)) %>% #Function to calculate mean
  rename(co2 = avg_co2) %>% #Rename column to prepare for join
  full_join(yrbp_new, by = c("yrbp" = "yrbp", "co2" = "co2"), #Merging data set
            keep = FALSE) 


combined_co2 #Review data

```
## 2 part c.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 



p <- combined_co2 %>% #Save data to ggplot variable to avoid long code chunk
  ggplot(mapping = aes(x = desc(yrbp), y = co2)) + #Define graph aesthetics
  geom_line(size = 1.1) + #Select to display line and size of 1.1
  labs( #Define graph titles
    x = "Years before present", #Visual title for x-axis
    y = "Carbon dioxide [ppm]" #Visual title for y-axis
  ) +
  theme_classic() + #Select background of graph
  scale_x_continuous( #Adjust scale x which is continuous variable
    breaks = c(-800000, -600000, -400000, -200000, 0), #Set breaks points to link to display relevant labels
    labels = c("800,000", "600,000", "400,000", "200,000", "0") #Define label correspond to breaks
  ) 
  
point_coords <- c(combined_co2$yrbp[1], combined_co2$co2[1]) #Define point curds for visual later
  
label_coords <- point_coords + c(-80000, -25) #Define another point for relevant graphics
  
p + annotate( #Function to use visual tools
    geom = "curve", #Selected curve to display
    x = label_coords[1], #X coord of label_coords
    y = label_coords[2], #Y coord of label_coords
    xend = point_coords[1], #X coord of point_coords
    yend = point_coords[2], #Y coord of point_coords
    curvature = -0.3, #Curvature of curve
    arrow = arrow(length = unit(3, "mm")), #Size of head
    alpha = 0.8, #Curve transparency
    colour = "#F8766D", #Curve color
    size = 1.2 #Curve size
  ) +
  annotate( #Function to use visual tools
    geom = "text", #Add text
    x = label_coords[1] -160000, #define x coord, relavent point according to question
    y = label_coords[2] -20, #define y coord, relavent point according to question
    label = "2021 average:
    417 ppm", #Text contents
    hjust = -0.1, vjust = -0.1, #Height & Vertical adjustments
    lineheight = 0.8,
    colour = "#F8766D" #Define text colour
  )
  
```
# Question 3
## 3 part a.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 
library("readxl") #Enable function to read xlsx files
library("janitor") #Enable clean_names()


sea_ice_1 <- read_xlsx(here("data", "nsidc_sea_ice_daily_extent.xlsx")) %>% #function to read xlsx file 
  select(!47:49) %>% #cut out irrelevant column
  rename(month = 
...1, day = ...2) %>% #Rename for easier manipulation 
  tidyr::fill(month, .direction = "down") %>% #Fill up empty rows with last missing values
  pivot_longer(cols = 3:46, names_to = c("year"), values_to = "extent") %>% #Put relevant column names into a column called "year", values to "extent"
  mutate(year = parse_date(year, format = "%Y")) %>% #Covert char to date
  mutate(year = year(year)) %>% #Covert date to year number only
  mutate(year = as.integer(year)) %>% #Covert column to integer
  mutate(day = as.integer(day)) %>% #Convert column to integer
  mutate(month = case_when( #For the lines below, months are bin into numbers
    month == "January" ~ 1L, #i.e. value of January will be changed to 1L, others are similar
    month == "February" ~ 2L,
    month == "March" ~ 3L,
    month == "April" ~ 4L,
    month == "May" ~ 5L,
    month == "June" ~ 6L,
    month == "July" ~ 7L,
    month == "August" ~ 8L,
    month == "September" ~ 9L,
    month == "October" ~ 10L,
    month == "November" ~ 11L,
    month == "December" ~ 12L,
    )
  ) 



```
## 3 part b.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

spec_baseline_extent <- sea_ice_1 %>% #Save data to join later
  group_by(month, year) %>% #Use for calculating monthly average extent for each year
  summarise(monthly_avg_extent = mean(extent, na.rm = TRUE)) %>% #Function to calculate mean
  filter(year == 1979) %>% #Select relevant year
  mutate(spec_baseline_ext = monthly_avg_extent) %>% #rename to better understands it
  select(month, spec_baseline_ext) #Select only useful column to prepare for merging


sea_ice_2 <- sea_ice_1 %>% #Save data as requested
  group_by(month, year) %>% #Use for calculating monthly average extent for each year
  summarise(monthly_avg_extent = mean(extent, na.rm = TRUE)) %>% #Function to calculate mean
  left_join(spec_baseline_extent, by = c("month" = "month" )) %>% #Merging data to allow the spec_baseline_ext i.e. 1979's baslines to insert
  mutate(proportion_baseline_extent = monthly_avg_extent / spec_baseline_ext) %>% #Calculating relative extent 
  select(year, month, proportion_baseline_extent) #Select relevant columns for easier manipulation
  
  

```
## 3 part c.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 
library("RColorBrewer") #Enable function to use the color packs

sea_ice_2 %>% 
  ggplot(mapping = aes(x = year, y = month, fill = proportion_baseline_extent)) + #Define graph aesthetics
  geom_tile() + #Select heat graph
  scale_x_continuous(expand = expansion(add = c(-1, -1))) + #Spacing from x-axis
  scale_y_continuous( #Define visuals on y-axis
    expand = expansion(add = c(0, 0)), #Spacing for y-axis
    breaks = c(1:12), #Define breaks numbers
    labels = c(month.name)) + #Define output labels for breaks
  labs( #Define graph titles
    title = "Sea ice (northern hemispher)", #Set title
    x = "Year", #Define title for x-axis
    y = "Month", #Define title for y-axis
    fill = "Proportion of 1979 extent" #Title for fill 
  ) + 
  theme_classic() + #Background
  scale_fill_distiller(palette = "RdPu") + #Select colour from RcolorBrewer
  theme(plot.title = element_text( #Adjust title functuin
                       hjust = 0.5, #Adjust height
                       size  = rel(1.5) #Adjust size
                     )
  ) 
```





# Question 4
## 4 part a.

```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

read_lines(here("data", "stop_and_search.csv")) #Read line to define readr function

stop_search_1 <- read_csv(here("data", "stop_and_search.csv")) %>% #Read and save data set
  clean_names() %>% #Remove spacing in column names
  rename(stops = number_of_stop_and_searches, population = population_by_ethnicity, rate = rate_per_1_000_population_by_ethnicity, year = time) %>% #Rename
  filter(ethnicity %in% c("All", "Black", "White", "Asian", "Other")) %>% #Filler relevant ethnicity
  mutate(stops = parse_number(stops, locale = locale(grouping_mark = ",")), #convert char to numbers and get rid of ,
         population = parse_number(population, locale = locale(grouping_mark = ",")), #convert char to numbers and get rid of ,
         rate = parse_double(rate)) %>% #Convert char to double
  select(year, ethnicity, legislation_type, geography, stops, population, rate) #Select relevant columns
  
stop_search_1 #Review table
```

## 4 part b.
```{r, eval = TRUE, echo = TRUE}
library("tidyverse") #Requiring "readr" function from the package
library("here") #Need to enable the "here" function
library("lubridate") #Enable function relating to dates 

rate_white <- stop_search_1 %>% #Save data to prepare for merge
  group_by(year, ethnicity, legislation_type, geography) %>% #group specific conditions for the search to happen
  summarise(mean_rate = mean(rate, na.rm = TRUE)) %>% #Calculate mean rate for each ethnicity
  filter(ethnicity == "White") %>% #Select white to merge later
  rename(rate_white = mean_rate) #Rename for easier understanding and manipulation

rate_white #Check table

stop_search_2 <- stop_search_1 %>% #Save new defined data set
  left_join(rate_white, by = c("year" = "year", "legislation_type" = "legislation_type", "geography" = "geography"), keep = FALSE) %>% #Add col:rate_white
  mutate(relaive_disparity = rate / rate_white) %>% #Calculate relative disparity
  rename(ethnicity = ethnicity.x) %>% #Tidy column
  select(!ethnicity.y) #Remove unnecessary column
  
stop_search_2 #Review table


```
## 4 part c.
1.

2.

3.

## 4 part d.

### Question 1
```{r, eval = TRUE, echo = TRUE}

stop_search_2 %>%
  
  


```
### Question 2

### Question 3

